
spring:   
  datasource:
    url: jdbc:mysql://172.17.0.8:3306/testdb
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
