
spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Barath@root123
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect